[General]
name = rasens
log_level = INFO
log_file = /var/log/rasens/service.log
pid_file = /var/run/rasens.pid

[Network]
enabled = false
port = 8080
bind_address = 0.0.0.0

[GPIO]
enabled = true
pin_17 = output,out,0
pin_18 = output,out,0
pin_22 = input,in,0

[Sensors]
poll_interval_ms = 1000
enable_logging = true

[DS18B20]
enabled = true

[EE895]
enabled = false
i2c_bus = 1
i2c_address = 0x00
sensor_id = ee895-1

[SDS011]
enabled = true
devices = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
